In [1]:
import sys
sys.path.append('../..')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from src.preprocessing_schoolid import SchoolYear

The preprocessing is handled by the SchoolYear class and its methods.

In [2]:
sy_1819 = SchoolYear('../../data/chicago_data_portal_csv_files/Chicago_Public_Schools_-_School_Profile_Information_SY1819.csv',
                     '../../data/chicago_data_portal_csv_files/.ipynb_checkpoints/Chicago_Public_Schools_-_School_Progress_Reports_SY1819-checkpoint.csv')

The original data set has 651 schools. 

In [3]:
sy_1819.merged_df.shape

(651, 276)

In [4]:
sy_1819.isolate_high_schools()
sy_1819.drop_no_gr_schools()
sy_1819.drop_no_student_schools()
sy_1819.make_percent_low_income()
sy_1819.drop_specialed_options().head()

School_ID  Legacy_Unit_ID  Finance_ID         Short_Name_sp  \
9      609754            1800       70070   CHICAGO MILITARY HS   
13     400051            1930       66141      NOBLE - NOBLE HS   
14     609678            1060       47021              JONES HS   
18     400085            3343       66394     ACERO - GARCIA HS   
20     400117            9034       66574  NOBLE - HANSBERRY HS   

                                         Long_Name_sp Primary_Category_sp  \
9                Chicago Military Academy High School                  HS   
13                         Noble - Noble College Prep                  HS   
14      William Jones College Preparatory High School                  HS   
18  Acero Charter Schools - Major Hector P. Garcia MD                  HS   
20                     Noble - Hansberry College Prep                  HS   

    Is_High_School  Is_Middle_School  Is_Elementary_School  Is_Pre_School  \
9             True             False                 False          False   
13            True             False                 False          False   
14            True             False                 False          False   
18            True             False                 False          False   
20            True             False                 False          False   

                                              Summary Administrator_Title  \
9   The oldest military academy in Chicago, Chicag...           Principal   
13  At Noble, our mission is to instill in our stu...            Director   
14  Nationally recognized for academic excellence,...           Principal   
18  Garcia, which opened in 2008, serves approxima...            Director   
20  Hansberry College Prep, the first public chart...            Director   

                 Administrator          Secondary_Contact_Title  \
9                Octavio Casas              Assistant Principal   
13               Mr. Ben Gunty              Assistant Principal   
14            Dr.Paul J Powers              Assistant Principal   
18  Ms. Lindsay Ahlgren-Blythe  Assistant Principal for Culture   
20      Ms. Kashawandra Wilson                              NaN   

        Secondary_Contact          Address_sp  City_sp  State_sp  Zip_sp  \
9           Octavio Casas    3519 S GILES AVE  Chicago  Illinois   60653   
13           Brooke Semel     1010 N NOBLE ST  Chicago  Illinois   60642   
14  Mrs. Therese Plunkett      700 S STATE ST  Chicago  Illinois   60605   
18      Kerry Bartholomew      4248 W 47TH ST  Chicago  Illinois   60632   
20                    NaN  8748 S ABERDEEN ST  Chicago  Illinois   60620   

        Phone_sp        Fax_sp  \
9   7.735350e+09  7.735350e+09   
13  7.738621e+09  7.732780e+09   
14  7.735349e+09  7.735349e+09   
18  7.735793e+09  7.733766e+09   
20  7.737293e+09  7.733042e+09   

                                CPS_School_Profile_sp  \
9   http://cps.edu/Schools/Pages/school.aspx?Schoo...   
13  http://cps.edu/Schools/Pages/school.aspx?Schoo...   
14  http://cps.edu/Schools/Pages/school.aspx?Schoo...   
18  http://cps.edu/Schools/Pages/school.aspx?Schoo...   
20  http://cps.edu/Schools/Pages/school.aspx?Schoo...   

                               Website_sp  \
9   http://www.chicagomilitaryacademy.org   
13    http://noblestreet.noblenetwork.org   
14        http://www.jonescollegeprep.org   
18             http://hg.aceroschools.org   
20    http://www.hansberrycollegeprep.org   

                                        Facebook  \
9                                            NaN   
13      http://www.facebook.com/noblecollegeprep   
14  https://www.facebook.com/JonesCollegePrepHS/   
18   https://www.facebook.com/garciaaceroschools   
20          https://www.facebook.com/BeNobleHCP/   

                               Twitter Youtube Pinterest  \
9                                  NaN     NaN       NaN   
13                                 NaN     NaN       NaN   
14  https://twitter.com/jonescollegehs  

After dropping K-8 schools, schools with no graduation rates or student counts, and schools with non-traditional missions, the dataset is left with 124 schools. 

In [5]:
sy_1819.merged_df.shape

(124, 277)

# Train Test Split


For test size, I will isolate 20% of the data for test data. During cross validation, I will create 4 folds out of 100, so that each fold will have just about the same number of records as the holdout set.

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(sy_1819.merged_df.drop("Graduation_Rate_School", axis =1),
                                                   sy_1819.merged_df["Graduation_Rate_School"], test_size=.2, 
                                                   random_state=42)

# FSM

The FSM only includes one predictor: `Student_Count_Total`, which has a high relative correlation to the target.  

In [7]:
df_train = X_train
df_train['Graduation_Rate_School'] = y_train


In [8]:
df_train[['Graduation_Rate_School', 'Student_Count_Total']].corr()

Graduation_Rate_School  Student_Count_Total
Graduation_Rate_School                1.000000             0.456953
Student_Count_Total                   0.456953             1.000000

In [9]:
from sklearn.model_selection import cross_validate
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

cv_fsm = cross_validate(lr, X_train[['Student_Count_Total']], y_train, cv=4, return_train_score=True)
print(cv_fsm['train_score'].mean())
print(cv_fsm['test_score'].mean())

0.20981763588780716
0.1937363728503241


In [12]:
from src.cps_model import cv_cps

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [13]:
cv_cps(lr, X_train, y_train, features=['Student_Count_Total'])

Train Scores
[0.22718754 0.19027046 0.22837148 0.19344107]
0.20981763588780716
0.018001686997550177
##########################
Test Scores
[0.15100894 0.23404639 0.13353977 0.25635039]
0.1937363728503241
0.052427753215864216
##########################
Coefficients from fit on full train set
[0.00840968] 73.07458560082212


The first simple model is high bias.  Only ~21% of the variance is explained.  The test score R^2 have a comprable mean R2, but have a high standard deviation.



In this simple model, for every 8 students, for every 100 students, the graduation rate goes up .84 points.  

## Add Low Income Students

In [14]:
cv_cps(lr, X_train, y_train, ['Student_Count_Total', 'Student_Count_Low_Income'])

Train Scores
[0.23435008 0.23517025 0.23228612 0.19969077]
0.2253743040234015
0.014865582640729598
##########################
Test Scores
[ 0.14946568 -0.0601912   0.06646287  0.25915872]
0.10372401833853784
0.11673563913742296
##########################
Coefficients from fit on full train set
[ 0.01111313 -0.00447168] 73.71533750473652


Adding low income student count makes the test scores drop significantly.

## Add Percent Low Income Students

In [15]:
cv_cps(lr, X_train, y_train, ['Student_Count_Total', 'perc_low_income'])

Train Scores
[0.31134971 0.25147838 0.25045948 0.27776989]
0.27276436536736653
0.02482178990015859
##########################
Test Scores
[0.14259012 0.29270778 0.28110586 0.22045112]
0.2342137189879206
0.059591782115318376
##########################
Coefficients from fit on full train set
[ 5.98248587e-03 -2.33127917e+01] 94.62223005709221


Percent low income has a positive effect on both the training and test scores.  

One test set is performing significantly worse than the ohers at .14 R^2.

## One Hot Encode Networks

In [18]:
from sklearn.impute import SimpleImputer

network_imputer = SimpleImputer(strategy='constant', fill_value='missing')

X_train['Network'] = network_imputer.fit_transform(X_train[['Network']])

In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import OneHotEncoder


# network_imputer = ColumnTransformer([('network_impute', SimpleImputer(strategy='constant', fill_value='missing'), ['Network'])], 
#                                          remainder='passthrough')


# network_transformer = ColumnTransformer( [('network_impute', SimpleImputer(strategy='constant', fill_value='missing'), ['Network']), 
#                                          ('network_ohe', OneHotEncoder(handle_unknown='ignore'), ['Network'])], 
#                                          remainder='passthrough')


network_ohe = ColumnTransformer([ 
                                          ('network_ohe', OneHotEncoder(handle_unknown='ignore'), ['Network'])], 
                                         remainder='passthrough')

network_pipe = make_pipeline(network_ohe, LinearRegression())

cv_cps(network_pipe, X_train, y_train, ['Student_Count_Total', 'perc_low_income', 'Network'])

Train Scores
[0.45440205 0.45415272 0.36770062 0.49544495]
0.442925083857444
0.04656940342440024
##########################
Test Scores
[ 0.30630564  0.28551318  0.50346845 -0.03052425]
0.2661907535277951
0.19126098814392287
##########################


Adding Network One Hot Encoded columns decreases the bias, but increases the vaiance.  There is even one negative R^2 score which is particularly worrisome.

# High Correlation 

In [ ]:
df_train.corr().iloc[-1].dropna().sort_values()

In [ ]:
df_train.corr().iloc[-1].dropna().sort_values(ascending=False)

In [ ]:
df_train[['Graduation_Rate_School', 'Student_Count_Low_Income']].corr()